### PR TITLE
feat(community): Stagehand tools integration

### PR DESCRIPTION
**Pull request by filip-michalsky**
This PR introduces an integration of Langchain with [Stagehand](https://github.com/browserbase/stagehand), the best in class AI web automation framework from Browserbase HQ.

Users can now use Stagehand web navigation tooling to power their agents with simple atomic web interactions!

### CODE REVIEW

File: docs/core_docs/docs/integrations/tools/stagehand.mdx [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+
+```bash
+npm install @browserbasehq/stagehand zod
+```
+
+2. Create a Stagehand Instance
+   If you plan to run the browser locally, you'll also need to install Playwright's browser dependencies.
+
+```bash
+npm exec playwright install
```
Comment (jacoblee93) [inline docs/core_docs/docs/integrations/tools/stagehand.mdx:30]: Should this be `npx` instead?

https://playwright.dev/docs/intro#updating-playwright

File: docs/core_docs/docs/integrations/tools/stagehand.mdx [hunk 2]
```diff
@@ -0,0 +1,112 @@
...
+```bash
+export ANTHROPIC_API_KEY="your-anthropic-api-key"
+```
+
+## Usage, Standalone, Local
+
+```typescript
+import { Stagehand } from "@browserbasehq/stagehand";
+import { StagehandActTool } from "./StagehandActTool";
+import { initializeAgentExecutor } from "@langchain/agents";
```
Comment (jacoblee93) [inline docs/core_docs/docs/integrations/tools/stagehand.mdx:52]: Ah this is quite old, we should show how to use this with LangGraph instead:

https://langchain-ai.github.io/langgraphjs/how-tos/create-react-agent/?h=create#code

File: examples/src/agents/stagehand_ai_web_browser.ts [hunk 3]
```diff
@@ -0,0 +1,42 @@
+import { StagehandToolkit } from "@langchain/community/agents/toolkits/stagehand";
```
Comment (jacoblee93) [inline examples/src/agents/stagehand_ai_web_browser.ts:1]: Just import it into your `.mdx` file so that you get type checking, linting etc.

File: libs/langchain-community/langchain.config.js [hunk 4]
```diff
@@ -65,6 +65,7 @@ export const config = {
     "agents/toolkits/aws_sfn": "agents/toolkits/aws_sfn",
     "agents/toolkits/base": "agents/toolkits/base",
     "agents/toolkits/connery": "agents/toolkits/connery/index",
+    "agents/toolkits/stagehand": "agents/toolkits/stagehand",
```
Comment (jacoblee93) [inline libs/langchain-community/langchain.config.js:68]: Also need to add this to `requiresOptionalDependencies` below

File: libs/langchain-community/package.json [hunk 5]
```diff
@@ -190,6 +192,7 @@
     "node-llama-cpp": "3.1.1",
     "notion-to-md": "^3.1.0",
     "officeparser": "^4.0.4",
+    "openai": "^4.72.0",
```
Comment (jacoblee93) [inline libs/langchain-community/package.json:195]: Did we need to add this?

File: libs/langchain-community/src/agents/toolkits/stagehand.ts [hunk 6]
```diff
@@ -0,0 +1,209 @@
...
+      new StagehandObserveTool(this.stagehand),
+    ];
+  }
+
+  static async fromStagehand(stagehand: Stagehand): Promise<StagehandToolkit> {
+    return new StagehandToolkit(stagehand);
+  }
+}
+
+abstract class StagehandToolBase extends Tool {
```
Comment (jacoblee93) [inline libs/langchain-community/src/agents/toolkits/stagehand.ts:36]: You probably want to extend `StructuredTool` instead since you can specify Zod schemas for tool inputs

**Review by jacoblee93 — CHANGES_REQUESTED** [review]
Thanks! See comments, please also remember to run `yarn format` and `yarn lint`.

File: libs/langchain-community/package.json (hunk 5 above)
Comment (filip-michalsky) [reply libs/langchain-community/package.json]: @jacoblee93 removed, will use `npm install @langchain/openai` instead.

File: docs/core_docs/docs/integrations/tools/stagehand.mdx (hunk 1 above)
Comment (filip-michalsky) [reply docs/core_docs/docs/integrations/tools/stagehand.mdx:30]: @jacoblee93 updated!

File: libs/langchain-community/langchain.config.js (hunk 4 above)
Comment (filip-michalsky) [reply libs/langchain-community/langchain.config.js:68]: done!

File: examples/src/agents/stagehand_ai_web_browser.ts (hunk 3 above)
Comment (filip-michalsky) [reply examples/src/agents/stagehand_ai_web_browser.ts:1]: added `StagehandToolkit` to my `.mdx` for type checking and linting.

File: libs/langchain-community/src/agents/toolkits/stagehand.ts (hunk 6 above)
Comment (filip-michalsky) [reply libs/langchain-community/src/agents/toolkits/stagehand.ts:37]: yessir! done

File: examples/src/agents/stagehand_ai_web_browser.ts (hunk 3 above)
Comment (filip-michalsky) [reply examples/src/agents/stagehand_ai_web_browser.ts:1]: note that for this I had to remove this dependency from the stagehand lib itself. It will only work with stagehand version 1.2.0+

File: libs/langchain-community/package.json (hunk 5 above)
Comment (filip-michalsky) [reply libs/langchain-community/package.json]: note that for this I had to remove this dependency from the stagehand lib itself. It will only work with stagehand version 1.2.0+

File: docs/core_docs/docs/integrations/tools/stagehand.mdx (hunk 2 above)
Comment (filip-michalsky) [reply docs/core_docs/docs/integrations/tools/stagehand.mdx]: done!

**Comment by filip-michalsky** [comment]
> Thanks! See comments, please also remember to run `yarn format` and `yarn lint`.

All changes addressed. I can't get this thing to compile anymore after merging in `main` but before I merge, the build works fine locally.

**Comment by filip-michalsky** [comment]
need to wait till `main` gets fixed? I synced and getting compile errors with `lancedb`

hain/community:build:internal: src/vectorstores/lancedb.ts:1:44 - error TS2307: Cannot find module '@lancedb/lancedb' or@langchain/community:build: arations.
@langchain/community:build: @langchain/community:build:internal: 
@langchain/community:build: @langchain/community:build:internal: 1 import { connect, Table, Connection } from "@lancedb/lancedb";
@langchain/community:build: @langchain/community:build:internal:                                              ~~~~~~~~~~~~~~~~~~
@langchain/community:build: @langchain/community:build:internal: 
@langchain/community:build: @langchain/community:build:internal: src/vectorstores/lancedb.ts:120:22 - error TS7006: Parameter 'item' implicitly has an 'an@langchain/community:build: 
@langchain/community:build: @langchain/community:build:internal: 
@langchain/community:build: @langchain/community:build:internal: 120     results.forEach((item) => {
@langchain/community:build: @langchain/community:build:internal:                          ~~~~
@langchain/community:build: @langchain/community:build:internal: 
@langchain/community:build: @langchain/community:build:internal: 
@langchain/community:build: @langchain/community:build:internal: Found 2 errors in the same file, starting at: src/vectorstores/lancedb.ts:1
@langchain/community:build: @langchain/community:build:internal: 
@langchain/community:build: @langchain/community:build:internal: Error: Command failed: tsc --outDir dist-cjs/ -p tsconfig.cjs.json
@langchain/community:build: @langchain/community:build:internal:     at ChildProcess.<anonymous> (file:///Users/filipmichalsky/Odyssey/clients/browserbase@langchain/community:build: njs/libs/langchain-scripts/dist/build/index.js:21:24)

File: libs/langchain-community/package.json [hunk 7]
```diff
@@ -190,6 +193,7 @@
     "node-llama-cpp": "3.1.1",
     "notion-to-md": "^3.1.0",
     "officeparser": "^4.0.4",
+    "openai": "^4.73.0",
```
Comment (filip-michalsky) [inline libs/langchain-community/package.json:196]: we need this for stagehand extract tool

File: libs/langchain-community/package.json [hunk 8]
```diff
@@ -319,6 +324,7 @@
     "neo4j-driver": "*",
     "notion-to-md": "^3.1.0",
     "officeparser": "^4.0.4",
+    "openai": "*",
```
Comment (filip-michalsky) [inline libs/langchain-community/package.json:327]: we need this for stagehand extract tool

File: libs/langchain-community/src/agents/toolkits/stagehand.ts (hunk 6 above)
Comment (jacoblee93) [reply libs/langchain-community/src/agents/toolkits/stagehand.ts:13]: You can also make base extend `StructuredTool` and just take a schema like `{ input: z.string() }`

But this is fine too

**Review by jacoblee93 — APPROVED** [review]
Thanks for your patience! Looks great, thank you!

File: yarn.lock
Comment (jacoblee93) [inline yarn.lock:1]: This is a really big diff and something is funky with running lint from root - investigating

Comment (filip-michalsky) [reply yarn.lock:1]: @jacoblee93 thank you, pls let me know if/how I can help

Comment (filip-michalsky) [reply yarn.lock:1]: I needed the langgraph dep for the example:

https://langchainjs-docs-6b8e73its-langchain.vercel.app/docs/integrations/tools/stagehand/#usage-with-langgraph-agents

Comment (jacoblee93) [reply yarn.lock:1]: I think resolved! Commented out the test for now - `@langchain/langgraph` also depends on community as a dev dep so it can cause some weird issues when developing locally

We can comment the test back in when needed
