### ISSUE TITLE
ToolNode not exported by langchain in v1.0.1

### ISSUE THREAD

**Issue by familygw** [langchain-ai/langchainjs#9232]
### Checked other resources

- [x] This is a bug, not a usage question. For questions, please use the LangChain Forum (https://forum.langchain.com/).
- [x] I added a very descriptive title to this issue.
- [x] I searched the LangChain.js documentation with the integrated search.
- [x] I used the GitHub search to find a similar question and didn't find it.
- [x] I am sure that this is a bug in LangChain.js rather than my code.
- [x] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
import { ToolNode } from "langchain";
```

### Error Message and Stack Trace (if applicable)

`ToolNode` **is not exported** from `"langchain"` in version `1.0.1`.

### Description

While trying to migrate from **LangGraphJS v0.3.x** to **v1.0.0**, I noticed that the following import was marked as deprecated:

```ts
import { ToolNode } from "@langchain/langgraph/prebuilt";
````

The deprecation warning explicitly says:

```
ToolNode has been moved to langchain package.
Update your import to:
import { ToolNode } from "langchain";
```

However, after updating the import as suggested, **VSCode and TypeScript report that `ToolNode` is not exported** from the `"langchain"` package.

---

## Steps to Reproduce

1. Install the following packages:

   ```bash
   npm install langchain@^1.0.1 @langchain/langgraph@^1.0.0 @langchain/core@^1.0.1 @langchain/community@^1.0.0 @langchain/openai@^1.0.0
   ```

2. Create a minimal test file:

   ```ts
   import { ToolNode } from "langchain"; // as recommended by migration warning
   console.log(ToolNode);
   ```

3. Compile or open in VSCode:

   ```bash
   tsc
   ```

4. TypeScript reports:

   ```
   Module '"langchain"' has no exported member 'ToolNode'.
   ```

---

## Expected Behavior

According to the deprecation message and the internal code references,
`ToolNode` should be re-exported from the main `langchain` package, allowing the following import to work:

```ts
import { ToolNode } from "langchain";
```

---

## Actual Behavior

`ToolNode` **is not exported** from `"langchain"` in version `1.0.1`.
Inspecting the distributed `dist/` folder of the `langchain` npm package shows that there is **no reference to `ToolNode` in the package exports**, even though the internal source code defines it.

---

## tsconfig.json

```json
{
  "compilerOptions": {
    "target": "ES2024",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "strict": true,
    "resolveJsonModule": true,
    "forceConsistentCasingInFileNames": true,
    "strictPropertyInitialization": false,
    "outDir": "./dist",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules", "**/*.spec.ts"]
}
```

---

## Additional Notes

* The **deprecation message** in `@langchain/langgraph` v1.0.0 suggests that `ToolNode` was moved to the `"langchain"` package.
* Inspecting the compiled code from `langchain@1.0.1` reveals that `ToolNode` exists internally but is **not included in the public export surface**.
* This likely indicates a missing or incomplete export statement in `packages/langchain/src/index.ts` during the refactor to the unified 1.0 structure.

---

## Temporary Workaround

Continue importing from the deprecated path until this issue is fixed:

```ts
import { ToolNode } from "@langchain/langgraph/prebuilt";
```

Although marked as deprecated, this import still works in v1.0.0.

### System Info

| Package | Version |
| --- | --- |
| langchain | ^1.0.1  |
| @langchain/core | ^1.0.1  |
| @langchain/community | ^1.0.0  |
| @langchain/langgraph | ^1.0.0  |
| @langchain/openai | ^1.0.0  |

**Node.js version:** v24+
**TypeScript version:** 5.9.3
**OS:** macOS (Intel)

**Comment by eyurtsev** [comment]
We decided to keep ToolNode in langgraph.prebuilt as it's mostly used for building custom langgraph workflows.

**Comment by eyurtsev** [comment]
We'll port additional improvements to the ToolNode that were made to support the langchain agent

**Comment by eyurtsev** [comment]
cc @sydney-runkle (for python version)

**Comment by hntrl** [comment]
@familygw Thanks for flagging! Like we mentioned we're keeping it around.

See https://github.com/langchain-ai/langgraphjs/pull/1745

**Comment by igortas** [comment]
@hntrl 
Still broken.
Cannot find module '@langchain/langgraph/prebuilt' or its corresponding type declarations

```
  System:
    OS: Linux 6.6 Arch Linux
  Binaries:
    Node: 25.3.0 - /usr/sbin/node
    npm: 11.7.0 - /usr/sbin/npm
    pnpm: 10.26.0 - /home/igor/.local/share/pnpm/pnpm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    typescript: ^5.9.3 => 5.9.3
```

```
   "langchain": "^1.2.10",
   "@langchain/community": "^1.1.4",
    "@langchain/core": "^1.1.15",
    "@langchain/google-genai": "^2.1.10",
    "@langchain/langgraph": "^1.1.0",
    "@langchain/langgraph-checkpoint-mongodb": "^1.1.6",
    "@langchain/mongodb": "^1.1.0"
```
